[build]
builder = "nixpacks"

[deploy]
startCommand = "cd client_dashboard && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn client_dashboard.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10