# Generated by Django 5.1.6 on 2025-08-05 03:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_url', models.URLField(blank=True, help_text='A URL para a qual enviaremos os eventos de chat.')),
                ('primary_color', models.CharField(default='#007BFF', help_text='Cor principal do chat em hexadecimal (ex: #007BFF).', max_length=7)),
                ('welcome_message', models.CharField(default='Olá! Como posso ajudar?', help_text='A primeira mensagem que o bot envia.', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
