# Generated by Django 5.1.6 on 2025-09-06 02:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Meu Chatbot', help_text='Nome do chatbot para identificação', max_length=100)),
                ('webhook_url', models.URLField(blank=True, help_text='A URL para a qual enviaremos os eventos de chat.')),
                ('primary_color', models.CharField(default='#007BFF', help_text='Cor principal do chat em hexadecimal (ex: #007BFF).', max_length=7)),
                ('welcome_message', models.CharField(default='Olá! Como posso ajudar?', help_text='A primeira mensagem que o bot envia.', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Chatbot',
                'verbose_name_plural': 'Configurações dos Chatbots',
                'ordering': ['-created_at'],
            },
        ),
    ]
