# Generated by Django 5.1.6 on 2025-08-17 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotconfig',
            options={'ordering': ['-created_at'], 'verbose_name': 'Configuração do Chatbot', 'verbose_name_plural': 'Configurações dos Chatbots'},
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='name',
            field=models.CharField(default='Meu Chatbot', help_text='Nome do chatbot para identificação', max_length=100),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to=settings.AUTH_USER_MODEL),
        ),
    ]
